### ISSUE TITLE
Cannot read properties of undefined (reading 'hashSync') [BUG]

### ISSUE THREAD

**Issue by lollobene** [josephgoksu/prime-nestjs#10]
**Describe the bug**
The bug happens when trying to create a new user through the /auth/register/ endpoint.

The error is in /src/auth/auth.service.ts:73:33
`userDTO.password = bcryptjs.hashSync(body.password, 10);`

Seems that _bcryptjs_ is **undefined**

**To Reproduce**
Steps to reproduce the behaviour:
1. install PostgreSQL docker container and configure it
2. run ./setup.sh
3. run 'npm run start'
3. trigger http request using insomnia (or postman)
4. See an error on the server console

**Expected behaviour**
The request should create a new user in the database

**Screenshots**
![image](https://user-images.githubusercontent.com/38067715/208154258-518c1ff9-19a9-41e2-942b-8d853bc9321d.png)

**Environment (please complete the following information):**
 - OS: macOS Ventura 13.1 (22C65)
 - Node: v16.18.1
 - npm: 8.19.2

**Additional context**
none

**Comment by lollobene** [comment]
I found a solution for that, just change some lines of code inside **src/auth/auth.service.ts**:

line 3: 
`import bcryptjs from 'bcryptjs';` becomes `import { compareSync, hashSync } from 'bcryptjs';`

line 46:
`bcryptjs.compareSync(...);` becomes `compareSync(...);`

line 73:
`bcryptjs.hashSync(...)` becomes `hashSync(...)`

**Comment by joeygoksu** [comment]
Thank you for bringing this up, @lollobene. It appears that the latest version of the library has differences in how their modules are exported.

If you resolve the issue on your side, a PR is highly appreciated. Thank you :)

**Comment by lollobene** [comment]
Yeah I just opened a PR :)
Thank you!
