### ISSUE TITLE
[BUG] bash ./setup.sh not work

### ISSUE THREAD

**Issue by kungfu321** [josephgoksu/prime-nestjs#14]
![Screenshot 2023-03-11 at 10 47 05](https://user-images.githubusercontent.com/10558363/224463320-7fb3abf8-8b13-40b8-b578-f0257da46b1e.png)

**Comment by servatj** [comment]
I think is a problem with the node version, using node 14 works. Wondering how you maintain a boilerplate accordingly to new node versions.

**Comment by josephgoksu** [comment]
I know it's been ages, but this problem has been fixed with https://github.com/josephgoksu/prime-nestjs/commit/526dc5a45e6805dd84738e55d14f34909290a042
