### ISSUE TITLE
[BUG] QuickSetup production script throws an error (sh: ts-node: not found)

### ISSUE THREAD

**Issue by omrumbakitemiz** [josephgoksu/prime-nestjs#5]
OS: Windows 11 x64
node: 17.3.0
npm: 8.3.0

Steps to produce error:

- open git-bash
- run `sh setup.sh`

after above commands script throws an error on console: `sh: ts-node: not found`

![image](https://user-images.githubusercontent.com/12871066/147849764-f92a4df3-877c-4c75-a5af-288eddf4a975.png)

**Comment by joeygoksu** [comment]
It seems like `ts-node` is missing which means that npm dev dependencies are missing.

https://github.com/joeygoksu/prime-nestjs/blob/3b9bb3244c78b2e26d81e264beceaf2965998294/setup.sh#L38

**Temporary solution:**

1. Go into the docker container
2. Run `npm install` or `yarn` command inside of the container
3. Run the migration script

**For the future:**

The new version will be released in 1-2 days. (includes new bash script) Thanks for letting us know.

**Comment by omrumbakitemiz** [comment]
Any update on new release 😇

**Comment by joeygoksu** [comment]
It's been a busy month but I will have a chance to update a couple of things next few days.

**Comment by alvindrakes** [comment]
@joeygoksu Love your repo, hope it receives better support and care! You're awesome.

**Comment by armensano** [comment]
Still have this error

**Comment by josephgoksu** [comment]
I know it's been ages, but I just fixed the error with https://github.com/josephgoksu/prime-nestjs/commit/526dc5a45e6805dd84738e55d14f34909290a042 :)
